[server]
server_ip =                      
# IP address of game server. Default: 127.0.0.1
server_port = 27960                                 
# Port of game server. Default: 27960
rcon_password =                
# Password for RCON
log_file = /Full path/games.log    
# Full path of the 'games.log' file (/home/USER/.qa3/q3ut4/games.log)

[rules]
show_rules = 0                                      
# Enable (1) or disable (0) displaying rules / rotation messages
rules_file = rules.txt
rules_frequency = 90                                
# Interval in seconds between each rule / rotation message. Default: 90
display = chat                                      
# Display rules as 'chat', 'bigtext' or 'server' message. Options: chat/bigtext/server. Default: chat

[bot]
ban_duration = 7
# Ban duration in days for the command "!ban <name>". Default: 7
warn_expiration = 240
# Expiration time of warnings in seconds. Set to 0 to disable this feature. Default 240
task_frequency = 60                          
# Interval in seconds for checking ping, warnings + spectators. Set to 0 to disable this feature. Default: 60
max_ping = 200                               
# Maximum allowed ping, player with higher ping will be kicked. Set to 0 to disable this feature. Default: 200
kick_spec_full_server = 10                   
# Warn / kick spectator when more than X players are connected. Set to 0 to disable this feature. Default: 10
teamkill_autokick = 1                        
# Enable (1) or disable (0) autokick for team killing. Regulars or higher levels will not get kicked. Default: 1
allow_teamkill_bots = 0                      
# Enable (1) or disable (0) team kills of bots without getting kicked. Default 0
noob_autokick = 0                            
# Enable (1) or disable (0) autokick of players with low score. Regulars or higher levels will not get kicked. Default: 0
spawnkill_autokick = 0                       
# Enable (1) or disable (0) autokick for spawn killing. Admins or higher levels will not get kicked. Default: 0
instant_kill_spawnkiller = 0                 
# Enable (1) or disable (0) instant kill for player doing spawn kill. Admins or higher levels will not get killed. Default: 0
spawnkill_warn_time = 3                      
# Spawnkill timer in seconds between player respawn and death to issue a warning. Recommended value: 2-5. Default: 3
bad_words_autokick = 0                       
# Enable (1) or disable (0) autokick for using bad words. Admins or higher levels will not get kicked. Default: 0
show_country_on_connect = 1                  
# Enable (1) or disable (0) displaying message "Player connected from...". Default: 1
show_first_kill = 1                          
# Enable (1) or disable (0) displaying message "firstblood" / "first nade kill". Default: 1
show_hit_stats_respawn = 1                   
# Enable (1) or disable (0) displaying hit statistics during respawn. Default: 1
show_multi_kill = 0                          
# Enable (1) or disable (0) displaying multi-kill and monster-kill messages. Default: 1
autobalancer = 0                             
# Enable (1) or disable (0) autobalancing of teams at the end of the round/match. Default: 0
allow_teams_round_end = 0                    
# Enable (1) or disable (0) allowing command !teams only at end of the round/match. Default: 0
limit_nextmap_votes = 0                      
# Enable (1) or disable (0) limiting successful nextmap votes. Default: 0
vote_delay = 0                               
# Interval in seconds for delaying votes after failed vote. Set to 0 to disable this feature. Default: 0
kill_survived_opponents = 0                  
# Enable (1) or disable (0) killing of survived opponents when bomb has been exploded/defused. Default: 0
spam_bomb_planted = 1                        
# Enable (1) or disable (0) spamming the message "Bomb has been planted" in global chat. Default: 0
spam_knife_kills = 0                         
# Enable (1) or disable (0) displaying player's knife kill series as bigtext. Default: 0
spam_nade_kills = 0                          
# Enable (1) or disable (0) displaying player's HE grenade kill series as bigtext. Default: 0
spam_headshot_hits = 1                       
# Enable (1) or disable (0) displaying player's headshot hit series as bigtext. Default: 0
reset_headshot_hits_mapcycle = 1             
# Enable (1) or disable (0) option to reset headshot stats for all players at map rotation. Default: 1
reset_kill_spree_mapcycle = 1                
# Enable (1) or disable (0) option to reset kill spree stats for all players at map rotation. Default: 1
verbose = 1                                       
# Enable (1) or disable (0) debug messages. Default: 0
botminplayers = 6
[mapcycle]
dynamic_mapcycle = 0                                
# Enable (1) or disable (0) dynamic mapcycle. If enabled, the rotation of small or big_cycle will be used. Default: 0
switch_count = 4                                    
# When server reaches the number of players, the map rotation will be switched to 'big_cycle' list. Default: 4
# Comma separated list of valid map names
small_cycle = ut4_turnpike, ut4_abbey
big_cycle = ut4_turnpike, ut4_algiers, ut4_casa, ut4_sanc

[lowgrav]
support_lowgravity = 0                              
# Enable (1) or disable (0) support for Low Gravity Server. Default: 0
gravity = 100                                       
# Set g_gravity to given value. Default: 800

[commands]
#cmd = desc syntax level short
help = display all available commands, ^7Usage: ^2!help, 0, h
forgive = forgive a player for team killing, ^7Usage: ^2!forgive ^7[<name>], 0, f
forgiveall = forgive all team kills, ^7Usage: ^2!forgiveall, 0, fa
forgivelist = list all players who killed you, ^7Usage: ^2!forgivelist, 0, fl
forgiveprev = forgive last team kill, ^7Usage: ^2!forgiveprev, 0, fp
grudge = grudge a player for team killing a grudged player will not be forgiven, ^7Usage: ^2!grudge ^7[<name>], 0
bombstats = display Bomb stats, ^7Usage: ^2!bombstats, 0
ctfstats = display Capture the Flag stats, ^7Usage: ^2!ctfstats, 0
freezestats = display freeze/thawout stats, ^7Usage: ^2!freezestats, 0
hestats = display HE grenade kill stats, ^7Usage: ^2!hestats, 0
hits = display hit stats, ^7Usage: ^2!hits, 0
hs = display headshot counter, ^7Usage: ^2!hs, 0
knife = display knife kill stats, ^7Usage: ^2!knife, 0
register = register yourself as a basic user, ^7Usage: ^2!register, 0
spree = display current kill streak, ^7Usage: ^2!spree, 0
stats = display current map stats, ^7Usage: ^2!stats, 0
teams = balance teams, ^7Usage: ^2!teams, 0
time = display the current server time, ^7Usage: ^2!time, 0
# user commands, level 1
regtest = display current user status, ^7Usage: ^2!regtest, 1
urtstats = display full player statistics, ^7Usage: ^2!urtstats ^7[<name>], 1
urttopstats = display the top players, ^7Usage: ^2!urttopstats, 1, topstats
# moderator commands, level 20
admintest = display current admin status, ^7Usage: ^2!admintest, 20
country = get the country of a player, ^7Usage: ^2!country ^7<name>, 20
lastmaps = list the last played maps, ^7Usage: ^2!lastmaps, 20
lastvote = display information about the last called vote, ^7Usage: ^2!lastvote, 20
leveltest = get the admin level for a given player or myself, ^7Usage: ^2!leveltest ^7[<name>], 20, lt
list = list all connected players, ^7Usage: ^2!list, 20
locate = display geolocation info of a player, ^7Usage: ^2!locate ^7<name>, 20, lc
mute = mute or un-mute a player, ^7Usage: ^2!mute ^7<name> [<duration>], 20
nextmap = display the next map in rotation, ^7Usage: ^2!nextmap, 20
poke = notify a player that he needs to move, ^7Usage: ^2!poke ^7<name>, 20
seen = display when a player was last seen, ^7Usage: ^2!seen ^7<name>, 20
shuffleteams = shuffle the teams, ^7Usage: ^2!shuffleteams, 20, shuffle
spec = move yourself to spectator, ^7Usage: ^2!spec, 20
warn = warn player, ^7Usage: ^2!warn ^7<name> [<reason>], 20, w
warninfo = display how many warnings a player has, ^7Usage: ^2!warninfo ^7<name>, 20, wi
warnremove = remove a player's last warning, ^7Usage: ^2!warnremove ^7<name>, 20, wr
warns = list the warnings, ^7Usage: ^2!warns, 20
warntest = test a warning, ^7Usage: ^2!warntest ^7<warning>, 20
# admin commands, level 40
admins = list all the online admins, ^7Usage: ^2!admins, 40
afk = force a player to spec because he is away from keyboard, ^7Usage: ^2!afk ^7<name>, 40
aliases = list the aliases of a player, ^7Usage: ^2!aliases ^7<name>, 40, alias
bigtext = display big message on screen, ^7Usage: ^2!bigtext ^7<text>, 40
exit = display last disconnected player, ^7Usage: ^2!exit, 40
find = display the slot number of a player, ^7Usage: ^2!find ^7<name>, 40
force = force a player to the given team, ^7Usage: ^2!force ^7<name> <blue/red/spec> [<lock>], 40
kick = kick a player, ^7Usage: ^2!kick ^7<name> <reason>, 40, k
nuke = nuke a player, ^7Usage: ^2!nuke ^7<name>, 40
regulars = display the regular players online, ^7Usage: ^2!regulars, 40, regs
say = say a message to all players, ^7Usage: ^2!say ^7<text>, 40, !!
tell = tell a message to a specific player, ^7Usage: ^2!tell ^7<name> <text>, 40
tempban = ban a player temporary for the given period, ^7Usage: ^2!tempban ^7<name> <duration> [<reason>], 40, tb
warnclear = clear the player warnings, ^7Usage: ^2!warnclear ^7<name>, 40, wc
# fulladmin commands, level 60
ban = ban a player for several days, ^7Usage: ^2!ban ^7<name> <reason>, 60, b
baninfo = display active bans of a player, ^7Usage: ^2!baninfo ^7<name>, 60, bi
ci = kick player with connection interrupt, ^7Usage: ^2!ci ^7<name>, 60
forgiveclear = clear a player's team kills, ^7Usage: ^2!forgiveclear ^7[<name>], 60, fc
forgiveinfo = display a player's team kills, ^7Usage: ^2!forgiveinfo ^7<name>, 60, fi
ping = display the ping of a player, ^7Usage: ^2!ping ^7<name>, 60
id = show the IP guid and authname of a player, ^7Usage: ^2!id ^7<name>, 60
kickbots = kick all bots, ^7Usage: ^2!kickbots, 60, kb
rain = enables or disables rain, ^7Usage: ^2!rain ^7<on/off>, 60
scream = scream a message in different colors to all players, ^7Usage: ^2!scream ^7<text>, 60
slap = slap a player (a number of times), ^7Usage: ^2!slap ^7<name> [<amount>], 60
status = report the status of the bot, ^7Usage: ^2!status, 60
swap = swap teams for player A and B, ^7Usage: ^2!swap ^7<name1> [<name2>], 60
version = display the version of the bot, ^7Usage: ^2!version, 60
veto = stop voting process, ^7Usage: ^2!veto, 60
# senioradmin commands, level 80
addbots = add bots to the game, ^7Usage: ^2!addbots, 80
banall = ban all players matching pattern, ^7Usage: ^2!banall ^7<pattern> [<reason>], 80, ball
banlist = display the last active 10 bans, ^7Usage: ^2!banlist, 80
bots = enables or disables bot support, ^7Usage: ^2!bots ^7<on/off>, 80
clear = clear all player warnings, ^7Usage: ^2!clear, 80, clear
cyclemap = cycle to the next map, ^7Usage: ^2!cyclemap, 80
exec = execute given config file, ^7Usage: ^2!exec ^7<filename>, 80
gear = set allowed weapons, ^7Usage: ^2!gear ^7<default/all/knife/pistol/shotgun/sniper>, 80
instagib = set Instagib mode, ^7Usage: ^2!instagib ^7<on/off>, 80
kickall = kick all players matching pattern, ^7Usage: ^2!kickall ^7<pattern> [<reason>], 80, kall
kill = kill a player, ^7Usage: ^2!kill ^7<name>, 80
lastadmin = display the last disconnected admin, ^7Usage: ^2!lastadmin, 80
lastbans = list the last 4 bans, ^7Usage: ^2!lastbans, 80, bans
lookup = search for a player in the database, ^7Usage: ^2!lookup ^7<name>, 80, l
makereg = make a player a regular (Level 2) user, ^7Usage: ^2!makereg ^7<name>, 80, mr
map = load given map, ^7Usage: ^2!map ^7<ut4_name>, 80
mapcycle = list the map rotation, ^7Usage: ^2!mapcycle, 80
maps = display all available maps, ^7Usage: ^2!maps, 80
maprestart = restart the map, ^7Usage: ^2!maprestart, 80, restart
moon = activate Moon mode (low gravity), ^7Usage: ^2!moon ^7<on/off>, 80
permban = ban a player permanent, ^7Usage: ^2!permban ^7<name> <reason>, 80, pb
putgroup = add a client to a group, ^7Usage: ^2!putgroup ^7<name> <group>, 80
rebuild = sync up all available maps, ^7Usage: ^2!rebuild, 80
setgravity = set the gravity (default: 800), ^7Usage: ^2!setgravity ^7<value>, 80
setnextmap = set the next map, ^7Usage: ^2!setnextmap ^7<ut4_name>, 80
swapteams = swap the current teams, ^7Usage: ^2!swapteams, 80
unban = unban a player from the database, ^7Usage: ^2!unban ^7<@ID>, 80
unreg = remove a player from the regular group, ^7Usage: ^2!unreg ^7<name>, 80
# superadmin commands, level 90
bomb = change gametype to Bomb, ^7Usage: ^2!bomb, 90
ctf = change gametype to Capture the Flag, ^7Usage: ^2!ctf, 90
ffa = change gametype to Free For All, ^7Usage: ^2!ffa, 90
gungame = change gametype to Gun Game, ^7Usage: ^2!gungame, 90
jump = change gametype to Jump, ^7Usage: ^2!jump, 90
lms = change gametype to Last Man Standing, ^7Usage: ^2!lms, 90
tdm = change gametype to Team Deathmatch, ^7Usage: ^2!tdm, 90
ts = change gametype to Team Survivor, ^7Usage: ^2!ts, 90
ungroup = remove admin level from a player, ^7Usage: ^2!ungroup ^7<name>, 90
password = set private server password, ^7Usage: ^2!password ^7[<password>], 90
reload = reload map, ^7Usage: ^2!reload, 90

[reasons]
obj = go for objective
camp = stop camping
spam = do not spam, shut-up!
lang = bad language
racism = racism is not tolerated
ping = fix your ping
afk = away from keyboard
tk = stop team killing
sk = stop spawn killing
spec = spectator too long on full server
score = score too low for this server
ci = connection interrupted
999 = connection interrupted
whiner = stop complaining about camp, lag or block
skill = skill too low for this server
name = do not use offensive names
wh = wallhack
insult = stop insulting
autojoin = use auto-join
abuse = stop abusing others
teams = keep the teams even

[geoip2]
path = /usr/share/GeoIP/GeoLite2-City.mmdb
# Full path of the 'GeoLite2-City.mmdb' file